[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
syndaxia_core = "ACFJxibNyTnVJVNTaYgBSi5YoFK3qy3xPqvmVmKynAC1"
syndaxia_treasury = "DvoZj1cKMi8DEvTxBgNEnj9Fhxx9PRAsVTEWEZ2e6YHx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 120000

[[test.genesis]]
address = "DvoZj1cKMi8DEvTxBgNEnj9Fhxx9PRAsVTEWEZ2e6YHx"
program = "tests/fixtures/syndaxia_treasury.so"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
